/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IMonitoringContract {
    function initializeCongestionControl(uint256 max_rate) external;

    function adjustCongestionControl(bool congestion_signal) external;

    function processTransaction(address sender, address recipient, uint256 amount) external;

    function getTransactionCount() external view returns (uint256);

    function getLatestValue() external view returns (uint256);

    function updateValue(uint256 new_value) external;

    function incrementTransactionCount() external;
}
